package com.michelslab.igcleaner;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.Color;
import android.net.Uri;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.*;

public class MainActivity extends Activity {
    private final ExecutorService io=Executors.newSingleThreadExecutor(); private SyncApi api; private LinearLayout body; private TextView status,title; private Button focusTab,auditTab,settingsTab; private String deviceId; private JSONArray currentItems=new JSONArray(); private JSONObject currentBatch; private final Set<String> opened=new HashSet<>();
    private int bg=Color.rgb(6,9,16),panel=Color.rgb(13,21,33),text=Color.rgb(239,246,255),muted=Color.rgb(142,158,180),cyan=Color.rgb(113,215,255),green=Color.rgb(99,209,167),gold=Color.rgb(239,189,98);
    @Override public void onCreate(Bundle b){super.onCreate(b);api=new SyncApi(this);deviceId=getSharedPreferences("igc_sync",MODE_PRIVATE).getString("device_id","");if(deviceId.isEmpty()){deviceId="android_"+UUID.randomUUID();getSharedPreferences("igc_sync",MODE_PRIVATE).edit().putString("device_id",deviceId).apply();}buildShell();showFocus();}
    private TextView tv(String s,int sp,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(c);v.setPadding(4,8,4,8);return v;}
    private Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}
    private void buildShell(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg);root.setPadding(18,18,18,12);title=tv("IG Cleaner Companion",22,text);root.addView(title);status=tv("Desktop ↔ Android",11,muted);root.addView(status);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);ScrollView sc=new ScrollView(this);sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));LinearLayout nav=new LinearLayout(this);nav.setOrientation(LinearLayout.HORIZONTAL);focusTab=btn("Focus");auditTab=btn("Audit");settingsTab=btn("Sync");focusTab.setOnClickListener(v->showFocus());auditTab.setOnClickListener(v->showAuditMenu());settingsTab.setOnClickListener(v->showSettings());nav.addView(focusTab,new LinearLayout.LayoutParams(0,-2,1));nav.addView(auditTab,new LinearLayout.LayoutParams(0,-2,1));nav.addView(settingsTab,new LinearLayout.LayoutParams(0,-2,1));root.addView(nav);setContentView(root);}
    private void clear(String h,String sub){body.removeAllViews();body.addView(tv(h,20,text));body.addView(tv(sub,12,muted));}
    private void note(String s){runOnUiThread(()->status.setText(s));}
    private void async(Job j){io.submit(()->{try{j.run();}catch(Exception e){note("Error: "+e.getMessage());}});} interface Job{void run()throws Exception;}
    private void showSettings(){clear("Sync","Usa el mismo Supabase que Desktop. La contraseña solo se usa para iniciar sesión.");EditText u=new EditText(this);u.setHint("Project URL");u.setText(api.getUrl());u.setTextColor(text);EditText k=new EditText(this);k.setHint("Anon / publishable key");k.setText(api.getKey());k.setTextColor(text);EditText e=new EditText(this);e.setHint("Email");e.setText(api.getEmail());e.setTextColor(text);EditText p=new EditText(this);p.setHint("Contraseña");p.setInputType(0x81);p.setTextColor(text);body.addView(u);body.addView(k);body.addView(e);body.addView(p);Button login=btn("Iniciar sesión");Button signup=btn("Crear cuenta");Button sync=btn("Sincronizar ahora");body.addView(login);body.addView(signup);body.addView(sync);login.setOnClickListener(v->{api.configure(u.getText().toString(),k.getText().toString(),e.getText().toString());async(()->{api.login(p.getText().toString());touchDevice();note("Conectado · Android");runOnUiThread(this::showFocus);});});signup.setOnClickListener(v->{api.configure(u.getText().toString(),k.getText().toString(),e.getText().toString());async(()->{api.signup(p.getText().toString());note("Cuenta creada. Si requiere confirmación de email, confírmala y luego inicia sesión.");});});sync.setOnClickListener(v->showFocus());}
    private void touchDevice()throws Exception{JSONObject d=new JSONObject().put("device_id",deviceId).put("device_type","android").put("label",Build.MANUFACTURER+" "+Build.MODEL).put("last_seen",Instant.now().toString());api.upsert("devices","device_id",new JSONArray().put(d));}
    private void showFocus(){clear("Focus","En móvil no se abren 20 perfiles a la vez. Toca uno, Instagram se abre y el checklist queda marcado. Al terminar, confirma la tanda.");if(!api.hasSession()){body.addView(tv("Conecta Supabase en Sync para recibir los Focus preparados de Desktop.",13,gold));return;}Button refresh=btn("Actualizar Focus");body.addView(refresh);refresh.setOnClickListener(v->loadBatches());loadBatches();}
    private void loadBatches(){async(()->{touchDevice();JSONArray a=api.get("focus_batches?select=*&status=in.(prepared,active)&order=created_at.desc&limit=30");runOnUiThread(()->renderBatches(a));});}
    private void renderBatches(JSONArray arr){clear("Focus","Selecciona una tanda preparada en Desktop o continúa una ya iniciada.");if(arr.length()==0){body.addView(tv("No hay Focus preparados todavía. En Desktop usa Ver siguiente Foco 20/30/40 y sincroniza.",13,muted));return;}for(int i=0;i<arr.length();i++){JSONObject b=arr.optJSONObject(i);Button x=btn(b.optString("label","Focus")+" · "+b.optInt("target_size")+" perfiles");x.setOnClickListener(v->loadBatch(b));body.addView(x);}}
    private void loadBatch(JSONObject batch){currentBatch=batch;opened.clear();async(()->{String id=URLEncoder.encode(batch.optString("id"),StandardCharsets.UTF_8);JSONArray a=api.get("focus_batch_items?select=*&batch_id=eq."+id+"&order=position.asc");currentItems=a;for(int i=0;i<a.length();i++){JSONObject r=a.optJSONObject(i);if(!"pending".equals(r.optString("status")))opened.add(r.optString("username"));}runOnUiThread(this::renderBatchItems);});}
    private void renderBatchItems(){clear(currentBatch.optString("label","Focus"),opened.size()+" / "+currentItems.length()+" abiertos · toca un perfil para abrir Instagram");for(int i=0;i<currentItems.length();i++){JSONObject r=currentItems.optJSONObject(i);String u=r.optString("username");JSONObject cx=r.optJSONObject("context");String context=cx==null?"":cx.optString("context","");CheckBox cb=new CheckBox(this);cb.setText("@"+u+(context.isEmpty()?"":"\n"+context));cb.setTextColor(text);cb.setChecked(opened.contains(u));cb.setButtonTintList(android.content.res.ColorStateList.valueOf(cyan));cb.setPadding(6,10,6,10);cb.setOnClickListener(v->{cb.setChecked(true);openProfile(u,r);});body.addView(cb);}Button finish=btn("Finalizar revisión · "+opened.size()+" / "+currentItems.length());finish.setEnabled(opened.size()==currentItems.length()&&currentItems.length()>0);finish.setOnClickListener(v->finalizeBatch());body.addView(finish);}
    private void openProfile(String u,JSONObject item){opened.add(u);renderBatchItems();Intent in=new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.instagram.com/"+u+"/"));try{in.setPackage("com.instagram.android");startActivity(in);}catch(Exception e){in.setPackage(null);startActivity(in);}async(()->{String bid=URLEncoder.encode(currentBatch.optString("id"),StandardCharsets.UTF_8),un=URLEncoder.encode(u,StandardCharsets.UTF_8);String now=Instant.now().toString();api.patch("focus_batch_items?batch_id=eq."+bid+"&username=eq."+un,new JSONObject().put("status","opened").put("opened_at",now).put("opened_device","android").put("updated_at",now));insertEvent(u,"opened",currentBatch.optString("module"),currentBatch.optString("id"),currentBatch.optString("label"),currentItems.length(),"",new JSONObject().put("via","android_checklist"));});}
    private void finalizeBatch(){new AlertDialog.Builder(this).setTitle("Finalizar revisión").setMessage("¿Confirmas que sí revisaste los "+currentItems.length()+" perfiles de esta tanda?").setNegativeButton("Cancelar",null).setPositiveButton("Sí, revisados",(d,w)->async(()->doFinalize())).show();}
    private void doFinalize()throws Exception{String now=Instant.now().toString(),bid=currentBatch.optString("id"),module=currentBatch.optString("module");JSONArray states=new JSONArray();for(int i=0;i<currentItems.length();i++){JSONObject it=currentItems.optJSONObject(i);String u=it.optString("username");String encB=URLEncoder.encode(bid,StandardCharsets.UTF_8),encU=URLEncoder.encode(u,StandardCharsets.UTF_8);api.patch("focus_batch_items?batch_id=eq."+encB+"&username=eq."+encU,new JSONObject().put("status","reviewed").put("reviewed_at",now).put("reviewed_device","android").put("updated_at",now));JSONObject st=new JSONObject().put("username",u).put("module",module).put("reviewed_at",now).put("reviewed_device","android").put("reviewed_device_id",deviceId).put("decision","").put("protected",false).put("context",it.optJSONObject("context")!=null?it.optJSONObject("context"):new JSONObject()).put("updated_at",now);states.put(st);insertEvent(u,"reviewed",module,bid,currentBatch.optString("label"),currentItems.length(),"",new JSONObject().put("via","android_batch_finalize"));}api.upsert("profile_state","username,module",states);api.patch("focus_batches?id=eq."+URLEncoder.encode(bid,StandardCharsets.UTF_8),new JSONObject().put("status","completed").put("completed_at",now).put("updated_at",now));insertEvent("","batch_completed",module,bid,currentBatch.optString("label"),currentItems.length(),"",new JSONObject().put("usernames",toUsernames(currentItems)));note("Tanda completada en Android · se sincronizará con Desktop");runOnUiThread(this::showFocus);}
    private JSONArray toUsernames(JSONArray a){JSONArray z=new JSONArray();for(int i=0;i<a.length();i++)z.put(a.optJSONObject(i).optString("username"));return z;}
    private void insertEvent(String u,String action,String module,String batch,String label,int size,String decision,JSONObject meta)throws Exception{JSONObject e=new JSONObject().put("id","ev_android_"+UUID.randomUUID()).put("event_at",Instant.now().toString()).put("username",u.isEmpty()?JSONObject.NULL:u).put("action",action).put("device_id",deviceId).put("device_type","android").put("device_label",Build.MANUFACTURER+" "+Build.MODEL).put("module",module==null?"unknown":module).put("batch_id",batch==null?JSONObject.NULL:batch).put("batch_label",label==null?"":label).put("batch_size",size).put("decision",decision==null?"":decision).put("meta",meta==null?new JSONObject():meta);api.upsert("audit_events","id",new JSONArray().put(e));}
    private void showAuditMenu(){clear("Audit","Audita lo revisado desde Android o Desktop sin modificar la fecha original de revisión.");Button a=btn("Últimos 20 revisados en Android");Button d=btn("Últimos 20 revisados en Desktop");Button oa=btn("Últimos 20 abiertos en Android");Button od=btn("Últimos 20 abiertos en Desktop");body.addView(a);body.addView(d);body.addView(oa);body.addView(od);a.setOnClickListener(v->loadAudit("android","reviewed"));d.setOnClickListener(v->loadAudit("desktop","reviewed"));oa.setOnClickListener(v->loadAudit("android","opened"));od.setOnClickListener(v->loadAudit("desktop","opened"));}
    private void loadAudit(String device,String action){async(()->{JSONArray rows=api.get("audit_events?select=*&device_type=eq."+device+"&action=eq."+action+"&order=event_at.desc&limit=200");LinkedHashMap<String,JSONObject> unique=new LinkedHashMap<>();for(int i=0;i<rows.length()&&unique.size()<20;i++){JSONObject r=rows.optJSONObject(i);String u=r.optString("username");if(!u.isEmpty()&&!unique.containsKey(u))unique.put(u,r);}runOnUiThread(()->renderAudit(device,action,new ArrayList<>(unique.values())));});}
    private void renderAudit(String device,String action,List<JSONObject> rows){clear("Audit · "+device,rows.size()+" perfiles · "+action);Set<String> seen=new HashSet<>();for(JSONObject r:rows){String u=r.optString("username");CheckBox c=new CheckBox(this);c.setText("@"+u+"\n"+r.optString("event_at"));c.setTextColor(text);c.setOnClickListener(v->{c.setChecked(true);seen.add(u);Intent in=new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.instagram.com/"+u+"/"));try{in.setPackage("com.instagram.android");startActivity(in);}catch(Exception e){in.setPackage(null);startActivity(in);}async(()->insertEvent(u,"audit_opened","audit",r.optString("batch_id"),"Audit "+device,rows.size(),"",new JSONObject().put("originDevice",device)));});body.addView(c);}Button done=btn("Marcar auditoría completada");done.setOnClickListener(v->async(()->{for(JSONObject r:rows){String u=r.optString("username");if(seen.contains(u))insertEvent(u,"audited","audit",r.optString("batch_id"),"Audit "+device,rows.size(),"",new JSONObject().put("originDevice",device).put("originEventId",r.optString("id")));}note("Auditoría Android registrada · "+seen.size()+" perfiles");runOnUiThread(this::showAuditMenu);}));body.addView(done);}
    @Override protected void onResume(){super.onResume();if(api!=null&&api.hasSession())note("Conectado · toca Actualizar para traer cambios recientes");}
}